# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*.*.*'
  pull_request:
#    paths:
#      - '*.py'
    branches:
      - '**'

jobs:
#
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#
#      - uses: actions/checkout@master
#
#      - name: Install poetry
#        run: pip install poetry
#
#      - name: Configure poetry
#        shell: bash
#        run: poetry config virtualenvs.in-project true
#
#      - name: Install dependencies
#        shell: bash
#        run: poetry install
#
#      - name: Run pytest
#        shell: bash
#        run: poetry run python -m pytest -p no:sugar -q tests/

  build:
#    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@master

      - name: Install poetry
        run: pip install poetry

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/*"
#          token: ${{ secrets.GITHUB_TOKEN }}
#          draft: false
#          prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish to PyPI
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}

